services:
  frontend:
    container_name: frontend-ocr
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    restart: always
    environment:
      API_URL: http://backend:8080

  backend:
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    build:
      context: ./ocr
