services:
  frontend:
    container_name: frontend-models
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "3000:5173"
    restart: always

  backend:
    restart: always
    expose:
      - "80"
    ports:
      - "80:80"
    build:
      context: ./ocr
